# Description: 我家云 Armbian 编译脚本
# License: MIT

name: Build Armbian For Chainedbox 5.15.y

on:
  workflow_dispatch:
    inputs:
      board:
        description: Target board
        required: true
        type: choice
        options:
          - l1pro
          - chainedbox
          - rock64
        default: chainedbox

      branch:
        description: Kernel and U-Boot branch
        required: true
        type: choice
        options:
          - legacy
          - current
          - edge
        default: current

      release:
        description: Upstream release
        required: true
        type: choice
        options:
          - buster
          - bullseye
          - sid
          - focal
          - jammy
        default: bullseye

      build_minimal:
        description: Minimal build
        required: true
        type: boolean
        default: true

      build_desktop:
        description: GUI desktop
        required: true
        type: boolean
        default: false

      bsp_freeze:
        description: Freeze kernel, U-Boot and DTB version
        required: true
        type: boolean
        default: true

      armbian_mirror:
        description: Package mirror site
        required: false
        type: string
        default: 'https://mirrors.bfsu.edu.cn'

      root_password:
        description: Root Password
        required: true
        type: string
        default: '1234'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_DIR: build/output/images
    steps:
    - id: install
      name: Install build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qqo=Dpkg::Use-Pty=0 update
        sudo -E apt-get -qqo=Dpkg::Use-Pty=0 install $(curl -fsSL git.io/depends-ubuntu-2004)

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: clone
      name: Clone the armbian repository
      run: |
        git clone --depth 1 https://github.com/armbian/build.git build
        #sudo cp -r ./config ./build
        #sudo cp -r ./userpatches ./build

    - name: Compile
      id: compile
      env:
        BOARD: ${{ inputs.board }}
        BRANCH: ${{ inputs.branch }}
        RELEASE: ${{ inputs.release }}
        BUILD_MINIMAL: ${{ inputs.build_minimal && 'yes' }}
        BUILD_DESKTOP: ${{ inputs.build_desktop && 'yes' }}
        ROOT_PWD: ${{ inputs.root_password }}
        KERNEL_ONLY: no
        KERNEL_CONFIGURE: no
        COMPRESS_OUTPUTIMAGE: sha,img
      run: build/compile.sh

    - id: patch
      name: Patch the image for Chainedbox
      env:
      run: |
        sudo ./rebuild-5.15.y.sh $IMAGE_DIR/*.img
        sudo xz -9evT0 $IMAGE_DIR/*.img

    - id: upload
      name: Upload to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Armbian-trunk_Chainedbox_5.15.y
        files: ${{ env.IMAGE_DIR }}
